# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-09 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('design', '0001_initial'),
        ('kalender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_Operasi', models.CharField(max_length=255)),
                ('waktu_mulai', models.DateTimeField(blank=True, null=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('keterangan', models.CharField(max_length=255)),
                ('status_operasi', models.BooleanField(default=False)),
                ('kalenderpenjadwalan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.KalenderPenjadwalan')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.Material')),
            ],
        ),
    ]
