# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-10 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operasi',
            name='kalenderpenjadwalan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kalender.KalenderPenjadwalan'),
        ),
    ]
