# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-28 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operasi', '0006_auto_20211129_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operasi',
            name='material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.Material'),
        ),
    ]
