# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-08 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operasi', '0007_auto_20211129_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operasi',
            name='kalenderpenjadwalan_id',
        ),
        migrations.RemoveField(
            model_name='operasi',
            name='lapakkerja_id',
        ),
        migrations.RemoveField(
            model_name='operasi',
            name='material_id',
        ),
        migrations.DeleteModel(
            name='Operasi',
        ),
    ]
