# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-08 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('design', '0017_auto_20211206_2227'),
        ('produk', '0017_auto_20211207_2006'),
        ('projectshop', '0015_lapakkerja_jadwal_lapak'),
        ('operasi', '0008_auto_20211208_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_mulai', models.DateTimeField(blank=True, null=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('status_operasi', models.BooleanField(default=False)),
                ('grup_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectshop.GrupKerja')),
                ('produkdijadwalkan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produk.ProdukDijadwalkan')),
                ('proses_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design.Proses')),
            ],
        ),
    ]
