# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-09 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operasi', '0009_operasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operasi',
            name='grup_id',
        ),
        migrations.RemoveField(
            model_name='operasi',
            name='produkdijadwalkan_id',
        ),
        migrations.RemoveField(
            model_name='operasi',
            name='proses_id',
        ),
        migrations.DeleteModel(
            name='Operasi',
        ),
    ]
