# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-09 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengaju', models.CharField(max_length=255)),
                ('tanggal_diajukan', models.DateTimeField(auto_now_add=True)),
                ('is_disetujui', models.BooleanField(default=False)),
                ('tanggal_persetujuan', models.DateTimeField(blank=True, null=True)),
                ('tanggal_berlaku', models.DateTimeField(blank=True, null=True)),
                ('keterangan', models.CharField(max_length=255)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.Material')),
            ],
        ),
    ]
