# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-15 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineeringorder', '0006_materialeo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialeo',
            name='penggantiMaterial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penggantiMaterial_material_eo', to='design.Material'),
        ),
        migrations.AlterField(
            model_name='materialeo',
            name='penyusun_produk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penyusun_produk_material_eo', to='design.Material'),
        ),
    ]
