# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-15 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineeringorder', '0007_auto_20211215_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringorder',
            name='material_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design.Material'),
        ),
    ]
