# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0007_auto_20211123_1926'),
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='kode_material',
            new_name='id_material',
        ),
        migrations.RemoveField(
            model_name='material',
            name='is_diubah',
        ),
        migrations.RemoveField(
            model_name='material',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='material',
            name='proses_id',
        ),
        migrations.RemoveField(
            model_name='material',
            name='tanggal_ditambahkan',
        ),
        migrations.RemoveField(
            model_name='material',
            name='tanggal_material_diubah',
        ),
        migrations.RemoveField(
            model_name='material',
            name='variant_id',
        ),
        migrations.AddField(
            model_name='material',
            name='penyusun_produk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produk.Material'),
        ),
        migrations.AddField(
            model_name='material',
            name='produk_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produk.Produk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='tanggal_berlaku',
            field=models.DateField(blank=True, null=True),
        ),
    ]
