# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20211124_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='penyusun_produk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design.Material'),
        ),
    ]
