# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_auto_20211124_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_berlaku',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='penggantiMaterial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penggantiMaterial_material_set', to='design.Material'),
        ),
        migrations.AddField(
            model_name='material',
            name='tanggalGanti',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='nama_supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='penyusun_produk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penyusun_produk_material_set', to='design.Material'),
        ),
    ]
