# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_auto_20211124_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='penggantiMaterial',
        ),
        migrations.RemoveField(
            model_name='material',
            name='penyusun_produk',
        ),
        migrations.RemoveField(
            model_name='material',
            name='produk_id',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
