# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-27 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0010_variant'),
        ('design', '0006_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='varian_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produk.Variant', to_field='id_varian'),
            preserve_default=False,
        ),
    ]
