# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-28 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineeringorder', '0004_auto_20211129_0043'),
        ('operasi', '0006_auto_20211129_0043'),
        ('design', '0007_material_varian_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='penggantiMaterial',
        ),
        migrations.RemoveField(
            model_name='material',
            name='penyusun_produk',
        ),
        migrations.RemoveField(
            model_name='material',
            name='varian_id',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
