# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-30 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0009_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proses',
        ),
    ]
