# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectshop', '0009_delete_kodeperalatan'),
        ('produk', '0013_auto_20211129_0044'),
        ('design', '0010_delete_proses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_modelproses', models.CharField(max_length=255)),
                ('durasi_proses', models.IntegerField()),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.Material')),
                ('produk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Produk')),
                ('proses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectshop.ProsesKerja')),
            ],
        ),
    ]
