# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-01 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0011_modelproses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelproses',
            name='material_id',
        ),
        migrations.RemoveField(
            model_name='modelproses',
            name='produk_id',
        ),
        migrations.RemoveField(
            model_name='modelproses',
            name='proses_id',
        ),
        migrations.DeleteModel(
            name='ModelProses',
        ),
    ]
