# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-01 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0013_proses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proses',
            name='id_proses',
            field=models.CharField(max_length=255),
        ),
    ]
