# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-06 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectshop', '0009_delete_kodeperalatan'),
        ('design', '0015_remove_proses_tipe_pengerjaan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proses',
            name='peralatan_id',
        ),
        migrations.AddField(
            model_name='proses',
            name='peralatan_id',
            field=models.ManyToManyField(to='projectshop.PeralatanKerja'),
        ),
    ]
