# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-06 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0016_auto_20211206_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proses',
            name='grup_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectshop.TipeKerja'),
        ),
    ]
