# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-11 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectshop', '0001_initial'),
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProsesKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_proses', models.CharField(max_length=255)),
                ('waktu_mulai', models.DateTimeField()),
                ('waktu_selesai', models.DateTimeField()),
                ('lapakkerja_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectshop.LapakKerja')),
                ('material_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produk.Material')),
                ('peralatankerja_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectshop.PeralatanKerja')),
                ('produk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Produk')),
            ],
        ),
    ]
