# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-30 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectshop', '0004_grupkerja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peralatankerja',
            name='availabilitas',
        ),
        migrations.RemoveField(
            model_name='peralatankerja',
            name='kodealat_id',
        ),
        migrations.AddField(
            model_name='peralatankerja',
            name='kode_alat',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
