# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-30 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectshop', '0006_auto_20211130_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProsesKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_proses', models.CharField(max_length=255)),
                ('nama_proses', models.CharField(max_length=255)),
                ('grup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectshop.GrupKerja')),
                ('peralatan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perlatan_id_PeralatanKerja_set', to='projectshop.PeralatanKerja')),
            ],
        ),
    ]
