# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-30 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectshop', '0007_proseskerja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lapakkerja',
            name='availabilitas',
        ),
        migrations.AddField(
            model_name='lapakkerja',
            name='kode_lapak',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
