# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-30 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectshop', '0008_auto_20211130_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KodePeralatan',
        ),
    ]
