# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-06 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectshop', '0012_auto_20211206_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapakkerja',
            name='aktif_bekerja',
            field=models.BooleanField(default=False),
        ),
    ]
