# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-06 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectshop', '0013_lapakkerja_aktif_bekerja'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapakkerja',
            name='grup_kerja',
            field=models.ManyToManyField(to='projectshop.GrupKerja'),
        ),
    ]
