# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-07 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectshop', '0014_lapakkerja_grup_kerja'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapakkerja',
            name='jadwal_lapak',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
