# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-11 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_material', models.CharField(max_length=255)),
                ('nama_supplier', models.CharField(max_length=255)),
                ('penyusun_produk', models.CharField(max_length=255)),
                ('is_diubah', models.BooleanField(default=False)),
                ('tanggal_material_diubah', models.DateField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_model', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_variant', models.CharField(max_length=255)),
                ('nama_atribut', models.CharField(max_length=255)),
                ('nilai_atribut', models.CharField(max_length=255)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Model')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='produk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Produk'),
        ),
    ]
