# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-09 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdukDijadwalkan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_design', models.BooleanField(default=False)),
                ('status_operasi', models.BooleanField(default=False)),
                ('variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Variant')),
            ],
        ),
    ]
