# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-10 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_produkdijadwalkan'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkdijadwalkan',
            name='jadwal_diminta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
