# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-17 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_produkdijadwalkan_jadwal_diminta'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkdijadwalkan',
            name='kode_pesanan',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
