# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-23 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_produkdijadwalkan_kode_pesanan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='nama_produk',
            new_name='id_brand',
        ),
        migrations.AddField(
            model_name='produk',
            name='id_model',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produk',
            name='id_varian',
            field=models.CharField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produk',
            name='nama_atribut',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produk',
            name='nama_brand',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produk',
            name='nama_model',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produk',
            name='nama_varian',
            field=models.CharField(default=6, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produk',
            name='nilai_atribut',
            field=models.CharField(default=7, max_length=255),
            preserve_default=False,
        ),
    ]
