# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-23 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0005_auto_20211123_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkdijadwalkan',
            name='variant_id',
        ),
        migrations.AddField(
            model_name='produkdijadwalkan',
            name='produk_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produk.Produk'),
            preserve_default=False,
        ),
    ]
