# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-23 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0006_auto_20211123_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkdijadwalkan',
            name='jadwal_diminta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
