# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0007_auto_20211123_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='nama_variant',
            new_name='nama_varian',
        ),
        migrations.RemoveField(
            model_name='model',
            name='produk_id',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='id_model',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='id_varian',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='nama_atribut',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='nama_model',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='nama_varian',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='nilai_atribut',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='model_id',
        ),
        migrations.AddField(
            model_name='model',
            name='id_model',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='id_varian',
            field=models.CharField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
