# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0008_auto_20211125_0050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
