# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0009_delete_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_varian', models.CharField(max_length=255, unique=True)),
                ('nama_varian', models.CharField(max_length=255)),
                ('nama_atribut', models.CharField(max_length=255)),
                ('nilai_atribut', models.CharField(max_length=255)),
            ],
        ),
    ]
