# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-28 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0011_auto_20211129_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='nama_variant',
            new_name='id_varian',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='id_variant',
            new_name='nama_varian',
        ),
    ]
