# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-02 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectshop', '0009_delete_kodeperalatan'),
        ('produk', '0013_auto_20211129_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkdijadwalkan',
            old_name='kode_pesanan',
            new_name='id_pesanan',
        ),
        migrations.RenameField(
            model_name='produkdijadwalkan',
            old_name='jadwal_diminta',
            new_name='tanggal_diminta',
        ),
        migrations.RemoveField(
            model_name='produkdijadwalkan',
            name='status_design',
        ),
        migrations.RemoveField(
            model_name='produkdijadwalkan',
            name='status_operasi',
        ),
        migrations.AddField(
            model_name='produkdijadwalkan',
            name='jam_diminta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produkdijadwalkan',
            name='lapak_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectshop.LapakKerja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produkdijadwalkan',
            name='nama_pesanan',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produkdijadwalkan',
            name='status_pengerjaan',
            field=models.CharField(choices=[('Selesai', 'Selesai'), ('Belum Selesai', 'Belum Selesai')], default='Belum Selesai', max_length=200),
        ),
        migrations.AlterField(
            model_name='produkdijadwalkan',
            name='produk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Produk'),
        ),
    ]
