# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-07 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0015_auto_20211206_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkdijadwalkan',
            name='lapak_id',
        ),
        migrations.AddField(
            model_name='produkdijadwalkan',
            name='lapak_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
