# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-07 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0016_auto_20211207_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkdijadwalkan',
            name='lapak_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectshop.LapakKerja'),
        ),
    ]
